version: "3"

services:
  # nginx
  nginx-web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    container_name: nginx-web
    restart: unless-stopped

    ports:
      - "8080:80"
    env_file:
      - ./config/.env.nginx_web

    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  php-app:
    build:
      context: ./app

    container_name: php-app

    volumes:
      - /app/vendor
      - ./app:/app
      - ./data:/data
    env_file:
      - ./config/.env.php_app

  # mysql
  mysql-db:
    image: mysql:8.3.0
    container_name: db-mysql-8.3.0
    restart: unless-stopped

    environment:
      - MYSQL_TCP_PORT=3306
    env_file:
      - ./config/.env.mysql

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
